import type { Metadata } from "next";
import { Nunito } from 'next/font/google'
import "./css/globals.css";
import Navbar from "@/components/Navbar";

const nunito = Nunito({
  subsets:["latin"],
  weight:["700","800", "600"]
})

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children}:{ children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={nunito.className}>
        <Navbar />
          { children }
      </body>
    </html>
  );
}
